### ISSUE TITLE
No Labs

### ISSUE THREAD

**Issue by CowPie** [Schemetrical/UBCScheduler#17] opened 2019-07-06 01:23 UTC
No labs are factored into the schedule for my ENGR classes.

**Comment by Schemetrical** [comment] 2019-07-08 18:41
I'll take a look as soon as possible

**Comment by CowPie** [comment] 2019-07-09 05:56
Much appreciated! Regardless, the tool is very useful. Thanks for your continued help with this service!

**Comment by Schemetrical** [comment] 2019-07-10 16:17
Could you give an example of which course that has no lab factored in?

I try to take the first section it sees as the "primary" section type (for example, lecture), but sometimes this can fail with engineering courses that have not-so-standard listings.

**Comment by CowPie** [comment] 2019-07-11 04:47
ENGR 325, APSC 253 and ENGR 335 (Okanagan campus) weren't working for me

**Comment by Schemetrical** [comment] 2019-07-12 06:21
I see what's happening. Unfortunately the scheduler doesn't have support for alternating days, and I chose to not schedule them since courses that had Mon* and Mon^ would fail to schedule, even though you should be able to take both.

I was going to recommend another scheduler, but it turns out it has support for neither okanagan nor alternating courses :(

I'll keep you updated if I manage to add this in, but chances are slim because now I have to account for 3 more types of time blocks: (unscheduled, scheduled,) alternating-first, alternating-second, alternating-both.

Duplicate of #1

**Closed as completed by Schemetrical** 2019-07-12 06:21 UTC
